name: Auto-Assign Trigger - Uday3 Branch Testing
on:
  # Removed global cron schedule - only run on Uday3 branch
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - Uday3  # Changed from main to Uday3 for testing

jobs:
  auto-assign-trigger:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run Enhanced Auto-Assign Trigger
        env:
          # Uday3 Branch Testing - Prioritize Uday3 variables
          SUPABASE_URL: ${{ secrets.SUPABASE_URL_UDAY3 }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY_UDAY3 }}
          LOG_LEVEL: INFO
          GITHUB_ACTIONS: "true"
          CHECK_INTERVAL: "60"
          MAX_LEADS_PER_BATCH: "50"
        run: python auto_assign_system.py worker
        
      - name: Log Results
        run: |
          echo "✅ Enhanced auto-assign trigger completed at $(date)"
          echo "🔄 Auto-assign system processed successfully" 