name: Auto-Assign Trigger - UDAY3 Branch Testing
on:
  schedule:
    - cron: '0 */1 * * *'  # Every hour at minute 0
    - cron: '15 */1 * * *'  # Every hour at minute 15
    - cron: '30 */1 * * *'  # Every hour at minute 30
    - cron: '45 */1 * * *'  # Every hour at minute 45
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - UDAY3  # Changed from main to UDAY3 for testing

jobs:
  auto-assign-trigger:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 */1 * * *' || github.event.schedule == '15 */1 * * *' || github.event.schedule == '30 */1 * * *' || github.event.schedule == '45 */1 * * *' || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run Enhanced Auto-Assign Trigger
        env:
          # UDAY3 Branch Testing - Prioritize UDAY3 variables
          SUPABASE_URL: ${{ secrets.SUPABASE_URL_UDAY3 }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY_UDAY3 }}
          LOG_LEVEL: INFO
          GITHUB_ACTIONS: "true"
          CHECK_INTERVAL: "60"
          MAX_LEADS_PER_BATCH: "50"
        run: python auto_assign_system.py worker
        
      - name: Log Results
        run: |
          echo "✅ Enhanced auto-assign trigger completed at $(date)"
          echo "🔄 Next run in 15 minutes" 