name: Auto-Assign Trigger - Uday3 Branch
on:
  schedule:
    - cron: '*/2 * * * *'  # Every 2 minutes - More frequent
    - cron: '* * * * *'  # Every minute
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - Uday3  # Also run when code is pushed

jobs:
  auto-assign-trigger-uday3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run Enhanced Auto-Assign Trigger (Uday3)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL_UDAY3 }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY_UDAY3 }}
          LOG_LEVEL: INFO
          GITHUB_ACTIONS: "true"
          CHECK_INTERVAL: "60"
          MAX_LEADS_PER_BATCH: "50"
        run: python auto_assign_system.py worker
        
      - name: Log Results
        run: |
          echo "✅ Enhanced auto-assign trigger completed at $(date) for Uday3 branch"
          echo "🔄 Next run in 1 minute" 