name: Continuous Monitor - Uday3 Branch
on:
  schedule:
    - cron: '0 */1 * * *'  # Every hour
    - cron: '30 */1 * * *'  # Every hour at 30 minutes
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - Uday3

jobs:
  monitor-and-run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run Meta Script (Uday3)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL_UDAY3 }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY_UDAY3 }}
          META_PAGE_ACCESS_TOKEN: ${{ secrets.META_PAGE_ACCESS_TOKEN }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
        run: |
          echo "🚀 Running Meta script for Uday3..."
          python metatosupabase.py
          
      - name: Run Knowlarity Script (Uday3)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL_UDAY3 }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY_UDAY3 }}
          KNOW_SR_KEY: ${{ secrets.KNOW_SR_KEY }}
          KNOW_X_API_KEY: ${{ secrets.KNOW_X_API_KEY }}
        run: |
          echo "🚀 Running Knowlarity script for Uday3..."
          python knowlaritytosupabase.py
          
      - name: Run Auto-Assign (Uday3)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL_UDAY3 }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY_UDAY3 }}
          LOG_LEVEL: INFO
          GITHUB_ACTIONS: "true"
          CHECK_INTERVAL: "60"
          MAX_LEADS_PER_BATCH: "50"
        run: |
          echo "🚀 Running Auto-Assign for Uday3..."
          python auto_assign_system.py worker
          
      - name: Log Completion
        run: |
          echo "✅ All scripts completed for Uday3 branch at $(date)"
          echo "🔄 Next run in 1 hour" 