name: Daily Script Runner
on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes - For all scripts
  workflow_dispatch:
jobs:
  run-all-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run knowlaritytosupabase.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          KNOW_SR_KEY: ${{ secrets.KNOW_SR_KEY }}
          KNOW_X_API_KEY: ${{ secrets.KNOW_X_API_KEY }}
        run: python knowlaritytosupabase.py
      - name: Run syncsalesforcetosupabase.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_SECURITY_TOKEN: ${{ secrets.SF_SECURITY_TOKEN }}
        run: python syncsalesforcetosupabase.py
      - name: Run metatosupabase.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          META_PAGE_ACCESS_TOKEN: ${{ secrets.META_PAGE_ACCESS_TOKEN }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
        run: python metatosupabase.py