# Uday3 Branch Script Runner - No Global Schedule
# This workflow only runs on Uday3 branch pushes and manual triggers
# Main branch variables are commented out to prevent conflicts
name: Uday3 Branch Script Runner
on:
  # Removed global cron schedule - only run on Uday3 branch
  workflow_dispatch:
  push:
    branches:
      - Uday3  # Only run on Uday3 branch

jobs:
  run-meta-script:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      # - name: Run knowlaritytosupabase.py (COMMENTED OUT)
      #   env:
      #     SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      #     SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_URL }}
      #     KNOW_SR_KEY: ${{ secrets.KNOW_SR_KEY }}
      #     KNOW_X_API_KEY: ${{ secrets.KNOW_X_API_KEY }}
      #   run: python knowlaritytosupabase.py
      - name: Run metatosupabase.py
        env:
          # Main branch variables (COMMENTED OUT for testing)
          # SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          # SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          
          # Branch-specific variables for Uday3 testing
          SUPABASE_URL: ${{ secrets.SUPABASE_URL_UDAY3 }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY_UDAY3 }}
          
          META_PAGE_ACCESS_TOKEN: ${{ secrets.META_PAGE_ACCESS_TOKEN }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
        run: python metatosupabase.py

  # SALESFORCE SCRIPT COMMENTED OUT - Authentication issues
  # run-salesforce-script:
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v3
  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.11'
  #     - name: Install dependencies
  #       run: pip install -r requirements.txt
  #     - name: Run syncsalesforcetosupabase.py
  #       env:
  #         # Main branch variables (COMMENTED OUT for testing)
  #         # SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  #         # SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
  #         
  #         # Branch-specific variables for Uday3 testing
  #         SUPABASE_URL: ${{ secrets.SUPABASE_URL_UDAY3 }}
  #         SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY_UDAY3 }}
  #         
  #         SF_USERNAME: ${{ secrets.SF_USERNAME }}
  #         SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
  #         SF_SECURITY_TOKEN: ${{ secrets.SF_SECURITY_TOKEN }}
  #       run: python syncsalesforcetosupabase.py
