name: Daily Script Runner - Uday3 Branch
on:
  schedule:
    - cron: '0 */1 * * *'  # Every hour at minute 0
    - cron: '30 */1 * * *'  # Every hour at minute 30
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - Uday3  # Also run when code is pushed

jobs:
  run-knowlarity-meta-scripts-uday3:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 */1 * * *' || github.event.schedule == '30 */1 * * *' || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Test Uday3 Database Connection
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL_UDAY3 }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY_UDAY3 }}
        run: |
          echo "🔍 Testing Uday3 database connection..."
          echo "SUPABASE_URL: ${SUPABASE_URL:0:30}..."
          echo "SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY:0:10}..."
          
      - name: Run knowlaritytosupabase.py (Uday3)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL_UDAY3 }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY_UDAY3 }}
          KNOW_SR_KEY: ${{ secrets.KNOW_SR_KEY }}
          KNOW_X_API_KEY: ${{ secrets.KNOW_X_API_KEY }}
        run: python knowlaritytosupabase.py
      - name: Test Meta Script Environment (Uday3)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL_UDAY3 }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY_UDAY3 }}
          META_PAGE_ACCESS_TOKEN: ${{ secrets.META_PAGE_ACCESS_TOKEN }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
        run: python test_meta_script.py
      - name: Run metatosupabase.py (Uday3)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL_UDAY3 }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY_UDAY3 }}
          META_PAGE_ACCESS_TOKEN: ${{ secrets.META_PAGE_ACCESS_TOKEN }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
        run: |
          echo "🚀 Starting Meta script for Uday3 branch..."
          echo "📊 Database URL: ${SUPABASE_URL:0:20}..."
          echo "🔑 Meta Token: ${META_PAGE_ACCESS_TOKEN:0:10}..."
          echo "📄 Page ID: $PAGE_ID"
          python metatosupabase.py
          echo "✅ Meta script completed!"

  run-salesforce-script-uday3:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run syncsalesforcetosupabase.py (Uday3)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL_UDAY3 }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY_UDAY3 }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_SECURITY_TOKEN: ${{ secrets.SF_SECURITY_TOKEN }}
        run: python syncsalesforcetosupabase.py 