name: Debug Uday3 Database and Auto-Assign
on:
  workflow_dispatch:  # Manual trigger only

jobs:
  debug-uday3-system:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Debug Uday3 Database and Auto-Assign
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL_UDAY3 }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY_UDAY3 }}
        run: |
          echo "🚀 Running Uday3 Database and Auto-Assign Debug..."
          python debug_uday3_database.py 